baseURL: "https://rilwan-adewoyin.github.io" 
title: Rilwan Adewoyin
pagination:
    pagerSize: 16
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Publications
          url: papers/
          weight: 1
        - name: Blog
          url: blog/
          weight: 2
        # - name: Search  
        #   url: /search/  
        #   weight: 3
        # - name: Courses
        #   url: courses/
        #   weight: 2
        # - name: Data
        #   url: data/
        #   weight: 3 
        # - name: Newsletter
        #   url: https://pmichaillat.substack.com
        #   weight: 4

params:
    description: "I'm a Machine Learning Researcher @ ECMWF working on the use of 
    Deep Learning for weather modelling."
    author: Rilwan Adewoyin
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: true
    disableScrollToTop: false
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Rilwan Adewoyin
          subtitle: "I'm a **Machine Learning Researcher** @ ECMWF working on the use of 
    Deep Learning for weather modelling."
          imageUrl: "profile.jpg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Rilwan Adewoyin
          buttons:
            - name: Publications
              url: /papers/
            - name: Blog
              url: /blog/
            # - name: Courses
            #   url: courses/
            # - name: Data
            #   url: data/
            # - name: Newsletter
            #   url: https://pmichaillat.substack.com
            # - name: Tags
            #   url: tags/
            # - name: Archive
            #   url: archive/
    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=SQxcHPMAAAAJ&hl=fr
        # - name: YouTube
        #   url: https://www.youtube.com/@pmichaillat
        - name: GitHub
          url: https://github.com/rilwan-adewoyin
        # - name: Substack
        #   url: https://pmichaillat.substack.com
        - name: Twitter
          url: https://twitter.com/rilakanni
        - name: Linkedin
          url: https://www.linkedin.com/in/rilwanade/
        - name: Meetings
          url: 

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Rilwan Adewoyin"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

# for search
# outputs:
#      home:
#          - HTML
#          - RSS
#          - JSON